language: python
dist: trusty

cache:
  apt: true
  # We use three different cache directory
  # to work around a Travis bug with multi-platform cache
  directories:
  - $HOME/.cache/pip
  - $HOME/download

env:
  global:
    # Directory where tests are run from
    - TEST_DIR=$HOME/tmp/test_dir
    - MODULE=grakel
    - WHEEL_FOLDER=wheelhouse
    - TWINE_USERNAME=ysig
    - DEPLOY_SDIST="false"
    - COVERAGE="false"
    - DEPLOY_WHEEL="false"
    - FLAKE="false"

# osx deps
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list python &>/dev/null || brew install python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list python3 &>/dev/null || brew install python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install pyenv-virtualenv; fi

matrix:
  include:
    - sudo: required
      services:
        - docker
      env:
        - PIP=pip
        - PYTHON=python
        - CIBW_BUILD="cp35-*"
        - FLAKE="true"
        - DEPLOY_SDIST="false"
    - sudo: required
      services:
        - docker
      env:
        - PIP=pip
        - PYTHON=python
        - CIBW_BUILD="cp36-*"
    - sudo: required
      services:
        - docker
      env:
        - PIP=pip
        - PYTHON=python
        - CIBW_BUILD="cp37-*"
    - sudo: required
      services:
        - docker
      env:
        - PIP=pip
        - PYTHON=python
        - CIBW_BUILD="cp27-manylinux1_x86_64"
    - sudo: required
      services:
        - docker
      env:
        - PIP=pip
        - PYTHON=python
        - CIBW_BUILD="cp27-manylinux1_i686"
    - os: osx
      language: generic
      sudo: required
      env:
        - TOXENV=py35
        - PIP=pip3
        - PYTHON=python3
        - COVERAGE="true"
        - CIBW_BUILD="cp27-macosx_10_6_intel"
    - os: osx
      language: generic
      sudo: required
      env:
        - PIP=pip3
        - PYTHON=python3
        - TOXENV=py35
        - CIBW_BUILD="cp35-macosx_10_6_intel"
    - os: osx
      language: generic
      sudo: required
      env:
        - PIP=pip3
        - PYTHON=python3
        - TOXENV=py35
        - CIBW_BUILD="cp36-macosx_10_6_intel"
    - os: osx
      language: generic
      sudo: required
      env:
        - PIP=pip3
        - PYTHON=python3
        - TOXENV=py35
        - CIBW_BUILD="cp37-macosx_10_6_intel"
script:
  - |
    if [[ "$FLAKE" == "true" ]]; then
        $PIP install flake8 --upgrade; flake8 $TRAVIS_BUILD_DIR/grakel;
    fi
  - $PIP install cibuildwheel
  - export CIBW_ENVIRONMENT="TEST_DIR=$TEST_DIR MODULE=$MODULE COVERAGE=$COVERAGE";
  - IFS= ; export CIBW_BEFORE_BUILD="$(cat ci_scripts/travis/install.sh)";
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        $PIP install numpy cython --upgrade;
    fi
  - IFS= ; export CIBW_TEST_COMMAND="$(cat ci_scripts/travis/test.sh)";
  - cibuildwheel --output-dir $WHEEL_FOLDER

after_success:
  - bash ci_scripts/travis/success.sh
