language: python

cache:
  apt: true
  # We use three different cache directory
  # to work around a Travis bug with multi-platform cache
  directories:
  - $HOME/.cache/pip
  - $HOME/download

env:
  global:
    # Directory where tests are run from
    - TEST_DIR=/tmp/test_dir/
    - MODULE=grakel
    - WHEEL_FOLDER=wheelhouse
    - TWINE_USERNAME=ysig

matrix:
  include:
    - sudo: required
      services:
        - docker
      env:
        - PIP=pip
        - COVERAGE="true"
        - DEPLOY_WHEEL=true
    - os: osx
      language: generic
      env:
        - PIP=pip2
        - COVERAGE="false"
        - DEPLOY_WHEEL=true

script:
  - $PIP install flake8 --upgrade && flake8 $TRAVIS_BUILD_DIR/grakel
  - $PIP install cibuildwheel==0.7.1
  - IFS= export CIBW_BEFORE_BUILD="$(cat ci_scripts/travis/install.sh)"
  - IFS= export CIBW_TEST_COMMAND="$(cat ci_scripts/travis/test.sh)"
  - cibuildwheel --output-dir $WHEEL_FOLDER
  - bash ci_scripts/travis/success.sh

