language: python

cache:
  apt: true
  # We use three different cache directory
  # to work around a Travis bug with multi-platform cache
  directories:
  - $HOME/.cache/pip
  - $HOME/download

env:
  global:
    # Directory where tests are run from
    - TEST_DIR=/tmp/test_dir/
    - MODULE=grakel
    - WHEEL_FOLDER=wheelhouse
    - TWINE_USERNAME=ysig
    - DEPLOY_SDIST="false"
    - COVERAGE="false"

matrix:
  include:
    - sudo: required
      services:
        - docker
      env:
        - PIP=pip
        - PYTHON=python
        - DEPLOY_WHEEL="false"
        - CIBW_SKIP="cp33-* cp34-* cp35-* cp36-* cp27-manylinux1_i686"
        - DEPLOY_SDIST="false"
    - sudo: required
      services:
        - docker
      env:
        - PIP=pip
        - PYTHON=python
        - DEPLOY_WHEEL="false"
        - CIBW_SKIP="cp33-* cp34-* cp35-* cp36-* cp27-manylinux1_x86_64"
        - DEPLOY_SDIST="false"
    - sudo: required
      services:
        - docker
      env:
        - PIP=pip
        - PYTHON=python
        - DEPLOY_WHEEL="false"
        - CIBW_SKIP="cp33-* cp34-* cp35-* cp27-*"
    - sudo: required
      services:
        - docker
      env:
        - PIP=pip
        - PYTHON=python
        - DEPLOY_WHEEL="false"
        - CIBW_SKIP="cp33-* cp34-* cp36-* cp27-*"
    - os: osx
      language: generic
      env:
        - PIP=pip2
        - PYTHON=python2
        - DEPLOY_WHEEL="true"
        - CIBW_SKIP="cp33-* cp34-* cp35-* cp36-* cp27-manylinux1_i686"
    - os: osx
      language: generic
      env:
        - PIP=pip2
        - PYTHON=python2
        - DEPLOY_WHEEL="true"
        - CIBW_SKIP="cp33-* cp34-* cp35-* cp36-* cp27-manylinux1_x86_64"
    - os: osx
      language: generic
      env:
        - PIP=pip2
        - PYTHON=python2
        - DEPLOY_WHEEL="true"
        - CIBW_SKIP="cp33-* cp34-* cp36-* cp27-*"
    - os: osx
      language: generic
      env:
        - PIP=pip2
        - PYTHON=python2
        - DEPLOY_WHEEL="true"
        - CIBW_SKIP="cp33-* cp34-* cp27-* cp35-*"
script:
  - $PIP install flake8 --upgrade && flake8 $TRAVIS_BUILD_DIR/grakel
  - $PIP install cibuildwheel==0.7.1
  - export CIBW_ENVIRONMENT="TEST_DIR=$TEST_DIR MODULE=$MODULE COVERAGE=$COVERAGE"
  - IFS= ; export CIBW_BEFORE_BUILD="$(cat ci_scripts/travis/install.sh)"
  - IFS= ; export CIBW_TEST_COMMAND="$(cat ci_scripts/travis/test.sh)"
  - echo $CIBW_BEFORE_BUILD
  - cibuildwheel --output-dir $WHEEL_FOLDER

after_success:
  - bash ci_scripts/travis/success.sh

