language: python

cache:
  apt: true
  # We use three different cache directory
  # to work around a Travis bug with multi-platform cache
  directories:
  - $HOME/.cache/pip
  - $HOME/download

env:
  global:
    # Directory where tests are run from
    - TEST_DIR=/tmp/test_dir/
    - MODULE=grakel
    - WHEEL_FOLDER=wheelhouse
    - TWINE_USERNAME=ysig
    - DEPLOY_SDIST="false"
    - COVERAGE="false"

matrix:
  include:
    - sudo: required
      services:
        - docker
      env:
        - PIP=pip
        - PYTHON=python
        - DEPLOY_WHEEL="false"
        - CIBW_SKIP="cp33-* cp34-* cp35-* cp36-* cp27-manylinux1_i686"
        - DEPLOY_SDIST="false"
    - sudo: required
      services:
        - docker
      env:
        - PIP=pip
        - PYTHON=python
        - DEPLOY_WHEEL="false"
        - CIBW_SKIP="cp33-* cp34-* cp35-* cp36-* cp27-manylinux1_x86_64"
        - DEPLOY_SDIST="false"
    - sudo: required
      services:
        - docker
      env:
        - PIP=pip
        - PYTHON=python
        - DEPLOY_WHEEL="false"
        - CIBW_SKIP="cp33-* cp34-* cp35-* cp27-*"
    - sudo: required
      services:
        - docker
      env:
        - PIP=pip
        - PYTHON=python
        - DEPLOY_WHEEL="false"
        - CIBW_SKIP="cp33-* cp34-* cp36-* cp27-*"
    - os: osx
      sudo: required
      language: generic
      env:
        - PIP=pip2
        - PYTHON=python2
        - DEPLOY_WHEEL="false"
        - CIBW_SKIP="cp33-* cp34-* cp35-* cp36-* cp27-manylinux1_i686"
    - os: osx
      sudo: required
      language: generic
      env:
        - PIP=pip2
        - PYTHON=python2
        - DEPLOY_WHEEL="false"
        - CIBW_SKIP="cp33-* cp34-* cp35-* cp36-* cp27-manylinux1_x86_64"
    - os: osx
      sudo: required
      language: generic
      env:
        - PIP=pip2
        - PYTHON=python2
        - DEPLOY_WHEEL="true"
        - CIBW_SKIP="cp33-* cp34-* cp36-* cp27-*"
    - os: osx
      sudo: required
      language: generic
      env:
        - PIP=pip2
        - PYTHON=python2
        - DEPLOY_WHEEL="false"
        - CIBW_SKIP="cp33-* cp34-* cp27-* cp35-*"
script:
  - $PIP install flake8 --upgrade && flake8 $TRAVIS_BUILD_DIR/grakel
  - $PIP install cibuildwheel==0.7.2
  - export CIBW_ENVIRONMENT="TEST_DIR=$TEST_DIR MODULE=$MODULE COVERAGE=$COVERAGE";
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        sudo ln -s /usr/local/Cellar/openssl/1.0.2l/bin/openssl /usr/bin/openssl;
        mkdir -p /usr/local/lib;
        sudo ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/;
        sudo ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/;
        openssl version -a;
        export PATH="/usr/local/bin:$PATH"
        openssl version -a;
        $PIP install numpy cython --upgrade;
        IFS= ; export CIBW_BEFORE_BUILD="$(cat ci_scripts/travis/install.sh)";
        IFS= ; export CIBW_TEST_COMMAND="{python} -c \"from grakel.datasets import fetch_dataset; Q = fetch_dataset('MUTAG', verbose=False)\" && nosetests $MODULE";
    else
        IFS= ; export CIBW_BEFORE_BUILD="$(cat ci_scripts/travis/install.sh)";
        IFS= ; export CIBW_TEST_COMMAND="$(cat ci_scripts/travis/test.sh)";
    fi
  - cibuildwheel --output-dir $WHEEL_FOLDER

after_success:
  - bash ci_scripts/travis/success.sh
